config/routes.rb
Ex2j::Application.routes.draw do

  resources :ufiles

  get "files/index"

  get "user/index"
  match "/user/logout" =>"user#logout"
  
  resources :user do
    resources :post do
      resources :comments  
    end 
  end

  get "home/index"
  match '/:controller/:action'
  match '/:controller/:action/:id'
  match "/post"  => "post#index"
  match "/files" => "ufiles#index"
  devise_for :users

  root :to => 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :post_id, :title
  belongs_to :post
  belongs_to :user
end

app/models/files.rb
class Files < ActiveRecord::Base
  attr_accessible :lock, :name, :share, :url, :user
  belongs_to :user
  has_many :filescomment
end

app/models/filescomment.rb
class Filescomment < ActiveRecord::Base
  attr_accessible :content, :ufile_id, :name
  belongs_to :ufile
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title, :ptype,:type_id
  belongs_to :user
  has_many :comment
end

app/models/type.rb
class Type < ActiveRecord::Base
  attr_accessible :name, :selftype
  belongs_to :user
end

app/models/ufile.rb
class Ufile < ActiveRecord::Base
	attr_accessible :name, :user_id,:src
	belongs_to :user
	has_many :filescomment
	has_attached_file :src
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible   :email, :password, :password_confirmation, :remember_me
  attr_accessible   :root,:sex,:right,:name,:birth,:image,:face
  has_attached_file :face,:styles=>{:tiny=>"100x100",:small=>"250x250",:medium=>"300x300",:thumb=>"100x100"}
  # attr_accessible :title, :body
  has_many :post
  has_many :ufile
  has_many :comment
  has_many :filescomment
  has_many :type
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def new
		user_id = params[:user_id]
		post_id = params[:post_id]
		@post = Post.find(post_id)
	end

	def show
	end

	def index

		user_id = params[:user_id]
		post_id = params[:post_id]
		@comments = current_user.post.find(post_id).comment.all

		respond_to do |f|
			f.html
			f.json { render :json => @comments }
		end
	# redirect_to "/users/sign_in"

	end

	def create
		
		title   = params[:comment][:title]
		content = params[:comment][:content]
		user_id = params[:user_id]
		post_id = params[:post_id]
		comment = User.find(user_id).post.find(post_id).comment.create(:title=>title,:content=>content)
		comment.save

		respond_to do |f|
			f.html{ redirect_to "/post/show/#{post_id}" }
		end
	end

end

app/controllers/files_controller.rb
class FilesController < ApplicationController
  def index
  	if current_user
  		
  	else
  		redirect_to "/user"
  	end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@user = current_user
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
	
	def index
		if user_signed_in?
			
			@types  = current_user.type.all
			type_id = params[:id]

			# if type_id == "all"
					@posts = current_user.post.all
			# 	else
			# 		@posts = current_user.post.find(:all,:conditions=>{:type_id=>"#{type_id}"})
			# end

			respond_to do |f|
				f.html
				f.json{ render :json => @posts }
			end

		else
			redirect_to "/users/sign_in"
		end
	end

	def new
		if current_user
			@user 	= current_user
			@post 	= current_user.post.new
			@types  = Type.find(:all,:conditions=>{:user_id=>current_user.id})
		else
			redirect_to "/users/sign_in"
		end	
	end

	def edit
		@user = current_user
		@post = current_user.post.find(params[:id])
	end

	def create
		if user_signed_in?
			@user   	 = User.find(current_user.id)
			title   	 = params[:post][:title]
			content 	 = params[:post][:content]
			user_id 	 = params[:user_id]
			type_id 	 = params[:post][:ptype]
			ptype		 = Type.find(type_id).name
			post 		 = Post.new(:title=>title,:content=>content,:ptype=>ptype,:type_id=>type_id)
			post.user_id = @user.id
			post.save

			respond_to do |f|
				f.html{redirect_to "/post"}
			end
		end
	end

	def show
		if current_user
		 	@post = Post.find(params[:id])
			respond_to do |f|
				f.html
				f.json{ render :json => @post }
			end
		else
			redirect_to "/"
		end
	end

	def update
		@post = Post.find(params[:id])
		respond_to do |format|
			if @post.update_attributes(params[:post])
				format.html { redirect_to "/post", notice: 'post was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: "edit" }
				format.json { render json: @post.errors, status: :unprocessable_entity }
			end
    	end
	end

	def info
		
	end
end

app/controllers/ufiles_controller.rb
class UfilesController < ApplicationController
  # GET /ufiles
  # GET /ufiles.json
  def index
    if current_user
    @ufiles = current_user.ufile.all
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @ufiles }
      end
    else
      redirect_to "/users/sign_in"
    end
  end

  # GET /ufiles/1
  # GET /ufiles/1.json
  def show
    @ufile = Ufile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ufile }
    end
  end

  # GET /ufiles/new
  # GET /ufiles/new.json
  def new
    if current_user
        @ufile = Ufile.new
        respond_to do |format|
          format.html # new.html.erb
          format.json { render json: @ufile }
        end
      else
        redirect_to "/users/sign_in"
    end
  end

  # GET /ufiles/1/edit
  def edit
    @ufile = Ufile.find(params[:id])
  end

  # POST /ufiles
  # POST /ufiles.json
  def create
    @ufile          = Ufile.new(params[:ufile])
    @ufile.user_id = current_user.id
    respond_to do |format|
      if @ufile.save
        format.html { redirect_to "/ufiles", notice: 'Ufile was successfully created.' }
        format.json { render json: @ufile, status: :created, location: @ufile }
      else
        format.html { render action: "new" }
        format.json { render json: @ufile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ufiles/1
  # PUT /ufiles/1.json
  def update
    @ufile = Ufile.find(params[:id])

    respond_to do |format|
      if @ufile.update_attributes(params[:ufile])
        format.html { redirect_to @ufile, notice: 'Ufile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ufile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ufiles/1
  # DELETE /ufiles/1.json
  def destroy
    @ufile = Ufile.find(params[:id])
    @ufile.destroy

    respond_to do |format|
      format.html { redirect_to ufiles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  
  def index
  	if current_user
  		@user = current_user
  	else
  		redirect_to "/users/sign_in"
  	end
  end

  def update
  	@user = current_user
  	@user.update_attributes(params[:user])
  	redirect_to "/user"
  end

  def logout
  		sign_out current_user
  		redirect_to "/"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/files_helper.rb
module FilesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/ufiles_helper.rb
module UfilesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comments/_form.html.erb
<% @comment = @post.comment.new %>
<%= form_for @comment,:url=>"/user/#{current_user.id}/post/#{@post.id}/comments",:method=>"post" do |p| %>
	<ul class="nav nav-list">
		<li><%= p.text_field :title,:style=>"width:400px" ,:placeholder=>"Title..."%></li>
		<li><%= p.text_area :content,:style=>"width:400px",:placeholder=>"Content..."%></li>
		<li><%= p.submit :class=>"btn" %></li>
	</ul>
<% end %>

app/views/comments/index.html.erb
<h1>post id  is <%=params[:user_id]%> <%=params[:post_id]%> ' comments here</h1>
<% @comments.each  do |f|%>
<div style="border:1px red solid;margin:10px">
	<%= f.title %><br />
	<%= f.content %><br />
</div>
<% end %>

app/views/files/index.html.erb
<h1>Files here</h1>

app/views/home/index.html.erb
<div class="row" style="margin-top:20px"></div>
<div class="container">

<div id="myCarousel" class="carousel slide" style="border:1px red solid;position:relative">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item"><img src="/images/wp1.jpg"></div>
    <div class="item"><img src="/images/wp.jpg"><div class="carousel-caption"><h4>sss</h4><p>ccccccccccccs</p></div></div>
    <div class="item"><img src="/images/wp2.jpg"></div>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>
<hr>

app/views/post/_form.html.erb
<%= form_for @post,:url=>"/user/#{current_user.id}/post",:method=>"post" do |p| %>
	<ul class="nav nav-list">
		<li>
			<%= p.text_field :title,:style=>"width:260px" ,:placeholder=>"Title..."%>
			<div class="input-append">
			<%= p.select :ptype,options_from_collection_for_select(@types,"id","name")%>
			<span class="add-on">
				<a id="adda" href="#myModal" data-toggle="modal">add</a>
			</span>
			</div>
		</li>
		<li>
			<%= p.text_area :content,:style=>"width:521px",:placeholder=>"Content..."%>
		</li>
		<li><%= p.submit %></li>
	</ul>
<% end %>
<div id="adddiv" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Modal header</h3>
  </div>
  <div class="modal-body">
    <input>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">关闭</button>
    <button class="btn btn-primary">Save changes</button>
  </div>
</div>

app/views/post/_form2.html.erb
<%= form_for @post,:url=>"/user/#{current_user.id}/post/#{@post.id}",:method=>"put" do |p| %>
	<ul class="nav nav-list">
		<li><%= p.text_field :title,:style=>"width:400px" ,:placeholder=>"Title..."%></li>
		<li><%= p.text_area :content,:style=>"width:400px",:placeholder=>"Content..."%></li>
		<li><%= p.submit %></li>
	</ul>
<% end %>

app/views/post/edit.html.erb
<div class="container">
<div class="well pricehover" style="height:470px">
		<div class="span5">
			<div class="container">
				<div class="container-fliud">
					<div class="row-fluid">
						<%= render 'form2' %>
					</div>
				</div>
			</div>
		</div>
		<div class="span3">
			<ul class="nav nav-list">
				<% @post.comment.each do |c| %>
				<div class="well pricehover">
					<li><%= c.title %></li>
				</div>
				<% end %>
			</ul>
		</div>
	</div>
</div>

app/views/post/index.html.erb
<div class="container">
<% unless @posts.size == 0 %>
<div id="myTab" class="tabbable tabs-left">
	<ul class="nav nav-tabs">
		<li class="active"><a href="" data-toggle="tab">index</a></li>
		<% @types.each do |type| %>
			<li id="<%= type.id %>" >
				<a id="<%= type.id %>" href="" data-toggle="tab"><%=type.name%></a></li>
		<% end %>
	</ul>
	<div class="tab-content offset2">
		<div class="accordion" id="accordion2">
			<% @posts.each do |post| %>
					<div class="accordion-group" id="<%=post.type_id%>"> 
						<div class="accordion-heading" style="">
							<a class="accordion-toggle"href="#<%=post.id%>" data-toggle="collapse"data-parent="#accordion2">
								<%=post.title%>
							</a>
						</div>
						<div id="<%=post.id%>" class="accordion-body collapse" style="height:0px">
							<div class="accordion-inner">
								<%=post.content%>
							</div>
						</div>
					</div>
			<% end %>
		</div>
	</div> 
</div>
</div>
<% else %>
<div class="jumbotron">
	<h1>Start here!</h1>
	<p class="lead">
		"Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus."
	</p>
	<a href="/post/new" class="btn btn-large btn-success">New notes</a>
</div>

<% end %>

app/views/post/new.html.erb
<div class="container" >
<div class="well">
	<div class="container">
		<div class="span1">
			<div class="container">
				<div class="container-fliud">
					<div class="row-fluid">
						<%= render 'form' %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>

app/views/post/show.html.erb
<div class="container">
<div class="well pricehover">
<div class="container">
<div class="span5">
<div>
	<%= @post.title %>
</div>
<h4>Comments below</h4>

<% @post.comment.each do |c| %>
<div class="well pricehover">
<ul class="nav nav-list">
	<li>
		<%= c.title %>
		<%= c.content%>
	</li>
</ul>
</div>
<% end %>
</div>
<div class="offset5"><%= render "comments/form" %></div>
</div>
</div>

app/views/ufiles/_form.html.erb
<%= form_for(@ufile) do |f| %>
  <% if @ufile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ufile.errors.count, "error") %> prohibited this ufile from being saved:</h2>

      <ul>
      <% @ufile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table class="table table-bordered table-striped">
  <tbody>
   <tr> 
      <td class="span5"><%= f.label :name %></td>
      <td><%= f.text_field :name%></td>
    </tr>
    <% if @ufile.src.path %>
    <tr> 
      <td><%= label_tag "Type" %></td>
      <td><%= select_tag ""%></td>
    </tr>
    <tr> 
      <td><%= label_tag "url" %></td>
      <td><%= @ufile.src.path[49,70] %></td>
    </tr>
    <% end %>
    <tr>
      <td></td>
      <td><%= f.file_field :src %></td>
    </tr>
    </tbody>
</table>
  <div class="actions">
    <%= f.submit :class=>"btn"%>
  </div>
<% end %>

app/views/ufiles/edit.html.erb
<div class="container">
<%= render 'form' %>
</div>

app/views/ufiles/index.html.erb
<div class="container"> 
<% @ufiles.each do |ufile| %>
  <table  class="table table-bordered table-striped">
    <tbody>
    <tr>
      <td class="span1">
      <% if ufile.name == "" %>
        **
      <% else %>
        <%= ufile.name[0,8] %>
      <% end %> 
  </td>
   <td class="span5"> 
      <% if ufile.src.exists? %>
        <%= ufile.src.path[49,70]%>
      <% else %>
          **
      <% end %> 
  </td>
  <td class="span2">
      <% if ufile.src.exists? %>
        <%= ufile.src.content_type.split("/")[1] %>
      <% else %>
          **
      <% end %> 
  </td>
   <td class="span2">
      <% if ufile.src.exists? %>
        <%= ufile.created_at.localtime.to_s[0,19] %>
      <% else %>
          **
      <% end %> 
  </td>
    <td class="span2">
      <%= link_to 'Down', ufile %>
      <%= link_to 'Edit', edit_ufile_path(ufile) %>
      <%= link_to 'Destroy', ufile, method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
    </tr> 
    </tbody>
  </table>
<% end %>
</div>

app/views/ufiles/new.html.erb
<div class="container">
<%= render 'form' %>
</div>

app/views/ufiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @ufile.name %>
</p>

<p>
  <b>User:</b>
  <%= @ufile.user_id %>
</p>


<%= link_to 'Edit', edit_ufile_path(@ufile) %> |
<%= link_to 'Back', ufiles_path %>

app/views/user/_form.html.erb
<div class="container">
	<%= form_for @user do |u| %>
	<div class="span4">
	<%= image_tag   @user.face.url(:small) %>
	<div style="margin-top:20px;width:auto">
	<%= u.file_field  :face %>
	</div>
	</div>
<div class="span3 offset3">
<ul class="nav nav-list">
	<li><%= u.text_field  :email,:placeholder=>"Email"  %></li>
	<li><%= u.text_field  :name ,:placeholder=>"Name"   %></li>
	<li><%= u.select  	  :sex  ,{:man=>"1",:lady=>"2"} %></li>
	<li><%= u.date_select :birth,:placeholder=>"Name",:start_year=>1949  %></li>
	<li><%= u.submit %></li>
</ul>
</div>

<% end %>
</div>

app/views/user/edit.html.erb
<%= render "form" %>

app/views/user/index.html.erb
<div class="container" >
<div class="well pricehover">
<div class="container" >

		<div class="">
			<div class="container">
				<div class="container-fliud span3">
					<div class="row-fluid">
						<%= render "form" %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>